pull_request_rules:

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: ask developers to review for a trusted author
    conditions:
      - label=ready
    actions:
      request_reviews:
        users:
          - lecrepont02

  - name: label on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict

  - name: dispatch gha workflow on conflicts
    conditions:
      - conflict
      - files=poetry.lock
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: conflicts_resolver.yaml
              inputs:
                remote: "{{ remote }}"
                head: "{{ head }}"
