pull_request_rules:

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: ask developers to review for a trusted author
    conditions:
      - label=ready
    actions:
      request_reviews:
        users:
          - lecrepont02

  - name: dispatch a gha
    conditions:
      - label=gha
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: phwes/simple_hello_world@v1
  #            inputs:
  #              name: steve
  #              age: 42
