pull_request_rules:

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: ask developers to review for a trusted author
    conditions:
      - label=ready
    actions:
      request_reviews:
        users:
          - lecrepont01

