version: 2.1

orbs:
  python: circleci/python@2.1.1
  mergifyio: mergifyio/ci-issues@0.0.2

jobs:
  run_tests:
    executor:
      name: python/default
      tag: 3.12.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            mkdir test_results
            poetry run pytest -vv --junitxml=test_results/report.xml
      - mergifyio/upload:
          token: MERGIFY_CI_ISSUES_TOKEN
          repository_url: <<pipeline.trigger_parameters.github_app.repo_url>>
          report_paths: test_results/report.xml
      - store_test_results:
          path: test_results

workflows:
  continuous_integration:
    jobs:
      - run_tests:
          context:
            - ci_secrets
