version: 2.1

orbs:
  python: circleci/python@2.2.0
  mergifyio: mergifyio/ci-issues@dev:test_version

jobs:
  run_tests:
    executor:
      name: python/default
      tag: 3.12.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            mkdir test_results
            poetry run pytest -vv --junitxml=test_results/report.xml
      - mergifyio/upload:
          report_paths: test_results/report.xml
      - store_test_results:
          path: test_results

workflows:
  continuous_integration:
    jobs:
      - run_tests:
          context:
            - ci_secrets
