version: 2.1

orbs:
  python: circleci/python@2.1.1
  mergisheim: krepon/mergisheim@0.0.2

jobs:
  run_tests:
    executor:
      name: python/default
      tag: 3.12.4
    parameters:
      actor:
        type: string
        default: krepon
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - mergisheim/greet:
          to: LECREPONT01
      - run:
          name: Echo test some parameters
          environment:
            HEAD_SHA: <<pipeline.git.revision>>
          command: |
            echo "Hello World << parameters.actor >> !" 
            echo "Current Job name: ${CIRCLE_JOB}"
            echo "Head SHA: ${HEAD_SHA}"
            echo "Head SHA from env var: ${CIRCLE_SHA1}"
            echo "Repo name: ${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: Run tests
          command: |
            mkdir test_results
            poetry run pytest -vv --junitxml=test_results/report.xml

      # NOTE: use as a step or in a separate job (share report in workspace in that case)
      # - mergify/ci_issues
      #     path: test_results/report.xml
      #     auth_token: ...

      - persist_to_workspace:
          # test usage of workspace sharing
          root: test_results
          paths:
            - report.xml

      - store_test_results:
          path: test_results


  display_tests_report:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Display reports
          command: |
            echo "Showing test results:\n"
            cat /tmp/workspace/report.xml


workflows:
  # each workflow has a workspace
  continuous_integration:
    jobs:
      - run_tests:
          actor: lecrepont01
#          context: org-context

      - display_tests_report:
          requires:
            - run_tests

#      # NOTE: If ran sequentially in another job (must use shared workspace)
#      - mergify_ci_issues_export:
#          requires:
#            - run_tests