version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  run_tests:
    executor:
      name: python/default
      tag: 3.12.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest --junitxml=mergisheim/tests/report.xml
      - run:
          name: Display reports
          command: cat mergisheim/tests/report.xml

workflows:
  continuous_integration:
    jobs:
      - run_tests