version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  run_tests:
#    working_directory: ~/project
    executor:
      name: python/default
      tag: 3.12.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Echo something
          command: echo "Hello World"
      - run:
          name: Run tests
          command: |
            mkdir test_results
            poetry run pytest -vv --junitxml=test_results/report.xml
      - run:
          name: Display reports
          command: cat test_results/report.xml
          when: always
      - store_test_results:
          path: tests_results


workflows:
  continuous_integration:
    jobs:
      - run_tests