version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  run_tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  continuous_integration:
    jobs:
      - run_tests