---
name: conflicts_resolver

on:
  workflow_dispatch:
    inputs:
      head-repo:
        description: "Full name of the head repository"
        type: string
        required: true
      head-branch:
        description: "Head branch"
        type: string
        required: true
      base-branch:
        description: "Base branch"
        type: string
        required: false
        default: "main"
      pull-request-number:
        description: "PR number to comment"
        type: number
        required: false
      author:
        description: "Author of the PR for the comment"
        type: string
        required: false

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PAT }}

      - name: resolve-poetry-conflicts
        uses: Mergifyio/gha-versionining-conflict-resolver@main
        with:
          head-repo: ${{ inputs.head-repo }}
          head-branch: ${{ inputs.head-branch }}
          base-branch: ${{ inputs.base-branch }}
          user: "lecrepont01"
          email: "leo.ecrepont@mergify.com"
          pull-request-number: ${{ inputs.pull-request-number }}
          author: ${{ inputs.author }}
