---
name: conflicts_resolver

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base branch"
        type: string
        required: false
        default: "main"

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: resolve-poetry-conflicts
        uses: Mergifyio/gha-versionining-conflict-resolver@main
        with:
          base: ${{ inputs.base }}
          github_token: ${{ secrets.MY_PAT }}
          user: lecrepont01
          email: leo.ecrepont@mergify.com
