---
name: conflicts_resolver

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base branch"
        type: string
        required: false
        default: "main"
      github_token:
        description: "Personal Access Token"
        type: string
        required: false
        default: ${{ secrets.MY_PAT }}

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: resolve-poetry-conflicts
        uses: Mergifyio/gha-versionining-conflict-resolver@main
        with:
          base: ${{ inputs.base }}
          github_token: ${{ inputs.github_token }}
