---
name: conflicts_resolver

on:
  workflow_dispatch:
    inputs:
      head-repo:
        description: "Full name of the head repository"
        type: string
        required: true
      head:
        description: "Head branch"
        type: string
        required: true
      base:
        description: "Base branch"
        type: string
        required: false
        default: "main"

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs
        run: echo head-repo=${{ inputs.head-repo }} ref=${{ inputs.head }}

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PAT }}
          repository: ${{ inputs.head-repo }}
          ref: ${{ inputs.head }}

      - name: resolve-poetry-conflicts
        uses: Mergifyio/gha-versionining-conflict-resolver@main
        with:
          head-repo: ${{ inputs.head-repo }}
          head: ${{ inputs.head }}
          base: ${{ inputs.base }}
          user: "lecrepont01"
          email: "leo.ecrepont@mergify.com"