---
name: conflicts_resolver

on:
  workflow_dispatch:
    inputs:
      remote:
        description: "The remote if different from origin"
        type: string
        required: false
        default: "origin"
      base:
        description: "Base branch"
        type: string
        required: false
        default: "main"
      head:
        description: "Head branch"
        type: string
        required: true

jobs:
  resolve_conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PAT }}
          ref: ${{ inputs.head }}

      - name: resolve-poetry-conflicts
        uses: Mergifyio/gha-versionining-conflict-resolver@main
        with:
          remote: ${{ inputs.remote }}
          base: ${{ inputs.base }}
          user: "lecrepont01"
          email: "leo.ecrepont@mergify.com"